<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->insert([
            [
                'category_title' => 'Laptop',
                'category_description' => 'A personal computer that can be easily moved and used in a variety of locations. ',
                'category_status' => 1,
                'category_image1' => 'category_1.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'category_title' => 'Desktop',
                'category_description' => 'A computer display area that represents the kinds of objects found on top of a physical desk',
                'category_status' => 1,
                'category_image1' => 'category_2.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'category_title' => 'Gaming PC',
                'category_description' => 'A specialized personal computer designed for playing video games. Gaming PCs typically differ from mainstream personal computers by using high-performance video cards and high core-count central processing units with raw performance.',
                'category_status' => 1,
                'category_image1' => 'category_3.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'category_title' => 'Tablet',
                'category_description' => 'A wireless, portable personal computer with a touchscreen interface. The tablet form factor is typically smaller than a notebook computer, but larger than a smartphone.',
                'category_status' => 1,
                'category_image1' => 'category_4.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'category_title' => 'Monitor',
                'category_description' => 'An electronic output device that is also known as a video display terminal (VDT) or a video display unit (VDU). It is used to display images, text, video, and graphics information generated by a connected computer via a computers video card.',
                'category_status' => 1,
                'category_image1' => 'category_5.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'category_title' => 'Tech Accessory',
                'category_description' => 'Tech Accessories are also known as computer peripherals and can include printers and scanners and storage devices. The best way to assess which computer peripherals would be useful for your business is to define your IT requirements, then match suitable accessories with these.',
                'category_status' => 1,
                'category_image1' => 'category_6.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'category_title' => 'Speakers',
                'category_description' => 'Speakers are made up of a cone, an iron coil, a magnet, and housing (case). When the speaker receives electrical input from a device, it sends the current through the causing it to move back and forth.',
                'category_status' => 1,
                'category_image1' => 'category_7.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'category_title' => 'Mouse or Keyboard',
                'category_description' => 'Keyboard || a panel of keys used for putting information including letters, words and numbers into your computer. Mouse || is a hand-operated pointing device.',
                'category_status' => 1,
                'category_image1' => 'category_8.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'category_title' => 'PC Part',
                'category_description' => 'A computer system is a set of integrated devices that input, output, process, and store data and information. Computer systems are currently built around at least one digital processing device. There are five main hardware components in a computer system: Input, Processing, Storage, Output and Communication devices.',
                'category_status' => 1,
                'category_image1' => 'category_9.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ],
           
        ]);
    }
}
